#!/bin/bash
TMP=$(mktemp)
IN=$(mktemp)
cat >$IN
cat $IN |while read line; do
NUM=$(echo "$line" |tr -dc '\t' |wc -c)
if [ -z "$MAX" ]; then
	MAX=0
fi
if [ $NUM -ge $MAX ]; then
	MAX=$NUM
	echo $MAX
fi
done|tail -n1 >$TMP;
MAX=$(cat $TMP);
rm $TMP;

cat $IN |while read line; do
NUM=$(echo "$line" |tr -dc '\t' |wc -c)
echo -n "$line"
echo -ne "\t"
if [ $NUM -lt $MAX ]; then
	perl -e "print \"20000\t\"x($MAX-$NUM);"
fi
echo
done
rm $IN
