#!/bin/bash
TMP=$(mktemp)
cat >$TMP
NUM=$1
OUTP=$2
function stamparighe(){
# in awk $1 => colonna Max, $8 => colonna SourceLine
out=$(cat $TMP | awk -v minrow=$1 -v maxrow=$2 '{FS=";";if($18 >=minrow && $18 <=maxrow){ if($12 == 1) { if (length($'$NUM') == 0) {printf("_\t");} else {printf("%s\t", $'$NUM');} } }}')
echo -e "$out" | tr ' ' '@'
}
(
. righe_cifrario
) | bash ../normalize_and_flip | bash ../convert_tabfigure_to_tikz_alt.sh $OUTP;
rm $TMP
