#!/bin/bash
TMP=$(mktemp)
cat >$TMP
NUM=$1
OUTP=$2
function stamparighe(){
# in awk $1 => colonna Max, $8 => colonna SourceLine
cat $TMP | awk -v minrow=$1 -v maxrow=$2 '{FS=";";if($18 >=minrow && $18 <=maxrow){ if($12 == 1) {printf "%i\t", $'$NUM';} }}'
echo
}
(
. righe_cifrario
)|sed s/999999/0/g | bash ../aggiustamatrici | bash ../convert_tabfigure_to_tikz.sh $OUTP ;
rm $TMP
